name: pocketllm_lite
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  go_router: ^17.0.0
  google_fonts: ^6.3.3
  flutter_markdown: ^0.7.7+1
  package_info_plus: ^9.0.0
  uuid: ^4.5.2
  transparent_image: ^2.0.1
  flutter_native_splash: ^2.4.7
  url_launcher: ^6.3.2

  hive: any
  flutter_colorpicker: ^1.1.0
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo.png"
  android_12:
    image: "assets/logo.png"
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/
